spring.application.name=AcademicAdvising

spring.datasource.url=jdbc:postgresql://localhost:5432/academic
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true

cloudinary.cloud_name=dokemixsa
cloudinary.api_key=998256514618684
cloudinary.api_secret=AP4uB6GbFZgBXmTUy_fYXkVOU9Q
cloudinary.secure=true

jwt.secret=Q2FhYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5ejEyMzQ1Njc4OTAxMjM0NTY3ODkw
jwt.expiration=86400000

#logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework.web.servlet.mvc.method.annotation=TRACE
#logging.level.org.springframework.web.multipart=DEBUG